name: scribes
description: Spiritually intelligent note-taking app with AI-assisted paraphrasing, scripture tagging, reminders, and private sharing.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management - BLoC Pattern
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Local Database - SQLite
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage & Preferences
  shared_preferences: ^2.2.2
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  
  # JSON Parsing
  json_annotation: ^4.8.1
  
  # Navigation
  go_router: ^12.1.1
  
  # UI Components
  flutter_slidable: ^3.0.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Scripture & Bible APIs
  # (Add specific packages for Bible APIs as needed)

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700